### ISSUE TITLE
Vercel Hosting

### ISSUE THREAD

**Issue by atovik** [MoLaadjal/Profile-Card-Component1#5]
Hello @MoLaadjal ,

Il faudrait t'inscrire à vercel (https://vercel.com). et y ajouter ton projet. c'est une plateforme d'hébergement de sites statiques. les déploiements sont automatisés, et c'est gratuit :-).

Merci de mettre à jour le Readme et y coller l'url fournie par vercel.

**Comment by MoLaadjal** [comment]
Done
